@echo off
echo Starting Mandiri Gapura AI...

echo Starting Backend server...
start "Backend" cmd /k "cd /d backend-go && go run ./cmd/gapura"

echo Starting Frontend server...
start "Frontend" cmd /k "cd /d frontend-angular && npm start"
